In [1]:
import numpy as np
import pandas as pd

In [2]:
ci = {90 : 1.645, 95 : 1.96, 99 : 2.576}
rng = np.random.default_rng(seed=100)
R = 5000

In [3]:
df7 = pd.read_csv('data/ames_prices.csv')
df7.head()

,Order,PID,area,price,MS.SubClass,MS.Zoning,Lot.Frontage,Lot.Area,Street,Alley,...,Screen.Porch,Pool.Area,Pool.QC,Fence,Misc.Feature,Misc.Val,Mo.Sold,Yr.Sold,Sale.Type,Sale.Condition
0,1,526301100,1656,215000,20,RL,141.0,31770,Pave,NaN,...,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal
1,2,526350040,896,105000,20,RH,80.0,11622,Pave,NaN,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
2,3,526351010,1329,172000,20,RL,81.0,14267,Pave,NaN,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
3,4,526353030,2110,244000,20,RL,93.0,11160,Pave,NaN,...,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
4,5,527105010,1629,189900,60,RL,74.0,13830,Pave,NaN,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal

In [4]:
df7['indicator']= (df7['Central.Air'] == 'Y').astype(int)
prp = df7['indicator'].mean()
print(f'Proportion of homes with central air : {round(prp,2)}')

Proportion of homes with central air : 0.93

In [5]:
col = df7['indicator'].to_numpy()
n = len(col)
bootstrap7 = []

for i in range(R):
    col_b = rng.choice(col, size=n, replace=True)
    mean_b7 = col_b.mean()
    bootstrap7.append(mean_b7)

In [6]:
se_hat7 = np.std(bootstrap7, ddof=1)
se_hat7

np.float64(0.004602823858818456)

In [7]:
for i,j in ci.items():
    lower7 = prp - j * se_hat7
    upper7 = prp + j * se_hat7
    print(f'For {i}% confidence interval is ({round(lower7,3)},{round(upper7,3)})')

    if lower7 < 0.90 < upper7:
        print(f'For {i}% : Value within CI. Fail to reject null hypothesis')
    else:
        print(f'For {i}% : Reject null hypothesis')

For 90% confidence interval is (0.926,0.941)
For 90% : Reject null hypothesis
For 95% confidence interval is (0.924,0.942)
For 95% : Reject null hypothesis
For 99% confidence interval is (0.921,0.945)
For 99% : Reject null hypothesis

In [8]:
df8 = pd.read_csv('data/ames_prices.csv')
df8.head()

,Order,PID,area,price,MS.SubClass,MS.Zoning,Lot.Frontage,Lot.Area,Street,Alley,...,Screen.Porch,Pool.Area,Pool.QC,Fence,Misc.Feature,Misc.Val,Mo.Sold,Yr.Sold,Sale.Type,Sale.Condition
0,1,526301100,1656,215000,20,RL,141.0,31770,Pave,NaN,...,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal
1,2,526350040,896,105000,20,RH,80.0,11622,Pave,NaN,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
2,3,526351010,1329,172000,20,RL,81.0,14267,Pave,NaN,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
3,4,526353030,2110,244000,20,RL,93.0,11160,Pave,NaN,...,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
4,5,527105010,1629,189900,60,RL,74.0,13830,Pave,NaN,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal

In [9]:
area_hyp = np.arcsinh(df8['area'])
price_hyp = np.arcsinh(df8['price'])

In [10]:
pear_corr = area_hyp.corr(price_hyp,'pearson')
print(f'The pearson correlation is : {round(pear_corr,3)}')

The pearson correlation is : 0.723

In [11]:
col1 = area_hyp.to_numpy()
col2 = price_hyp.to_numpy()
bootstrap8 = []

for i in range(R):
    r = rng.integers(0,n,size=n)
    col1_b = col1[r]
    col2_b = col2[r]
    pear_corr_b = np.corrcoef(col1_b,col2_b)[0,1]
    bootstrap8.append(pear_corr_b)

In [12]:
se_hat8 = np.std(bootstrap8, ddof=1)
se_hat8

np.float64(0.010026036907082472)

In [13]:
for i,j in ci.items():
    lower8 = pear_corr - j * se_hat8
    upper8 = pear_corr + j * se_hat8
    print(f'For {i}% confidence interval is ({round(lower8,3)},{round(upper8,3)})')

    if lower8 < 0 < upper8:
        print(f'For {i}% : Value within CI. Fail to reject null hypothesis')
    else:
        print(f'For {i}% : Reject null hypothesis')

For 90% confidence interval is (0.707,0.74)
For 90% : Reject null hypothesis
For 95% confidence interval is (0.704,0.743)
For 95% : Reject null hypothesis
For 99% confidence interval is (0.697,0.749)
For 99% : Reject null hypothesis

In [14]:
df9 = pd.read_csv('data/metabric.csv')
df9.head()

,Age at Diagnosis,Type of Breast Surgery,Cancer Type,Chemotherapy,Hormone Therapy,Lymph nodes examined positive,Mutation Count,Nottingham prognostic index,Overall Survival (Months),Overall Survival Status,Radio Therapy,TMB (nonsynonymous),Tumor Size,Tumor Stage
0,43.19,BREAST CONSERVING,Breast Cancer,NO,YES,0.0,2.0,4.020,84.633333,0:LIVING,YES,2.615035,10.0,1.0
1,48.87,MASTECTOMY,Breast Cancer,YES,YES,1.0,2.0,4.030,163.700000,1:DECEASED,NO,2.615035,15.0,2.0
2,47.68,MASTECTOMY,Breast Cancer,YES,YES,3.0,1.0,4.050,164.933333,0:LIVING,YES,1.307518,25.0,2.0
3,76.97,MASTECTOMY,Breast Cancer,YES,YES,8.0,2.0,6.080,41.366667,1:DECEASED,YES,2.615035,40.0,2.0
4,78.77,MASTECTOMY,Breast Cancer,NO,YES,0.0,4.0,4.062,7.800000,1:DECEASED,YES,5.230071,31.0,4.0

In [15]:
overall_mean = df9['Overall Survival (Months)'].mean()
print(f'The estimated mean of overall survival is : {round(overall_mean,3)} months or {round(overall_mean/12,0)} years')

The estimated mean of overall survival is : 129.094 months or 11.0 years

In [16]:
mon = df9['Overall Survival (Months)'].to_numpy()
n = len(mon)
bootstrap9 = []

for i in range(R):
    mon_b = rng.choice(mon, size=n, replace=True)
    mean_b9 = mon_b.mean()
    bootstrap9.append(mean_b9)

In [17]:
se_hat9 = np.std(bootstrap9, ddof=1)
se_hat9

np.float64(2.166857968299496)

In [18]:
for i,j in ci.items():
    lower9 = overall_mean - j * se_hat9
    upper9 = overall_mean + j * se_hat9
    print(f'For {i}% confidence interval is ({round(lower9,3)},{round(upper9,3)}) in months')
    print(f'For {i}% confidence interval is ({round(lower9/12,1)},{round(upper9/12,1)}) in years')

    if lower9 < 120 < upper9:
        print(f'For {i}% : Value within CI. Fail to reject null hypothesis')
    else:
        print(f'For {i}% : Reject null hypothesis')

For 90% confidence interval is (125.53,132.659) in months
For 90% confidence interval is (10.5,11.1) in years
For 90% : Reject null hypothesis
For 95% confidence interval is (124.847,133.341) in months
For 95% confidence interval is (10.4,11.1) in years
For 95% : Reject null hypothesis
For 99% confidence interval is (123.512,134.676) in months
For 99% confidence interval is (10.3,11.2) in years
For 99% : Reject null hypothesis

In [19]:
df10 = pd.read_csv('data/nhanes_data_17_18.csv',low_memory=False)
df10.head()

,SEQN,GeneralHealthCondition,EverBreastfedOrFedBreastmilk,AgeStoppedBreastfeedingdays,AgeFirstFedFormuladays,AgeStoppedReceivingFormuladays,AgeStartedOtherFoodbeverage,AgeFirstFedMilkdays,TypeOfMilkFirstFedWholeMilk,TypeOfMilkFirstFed2Milk,...,DaysSmokedCigsDuringPast30Days,AvgCigarettesdayDuringPast30Days,TriedToQuitSmoking,TimesStoppedSmokingCigarettes,HowLongWereYouAbleToStopSmoking,UnitOfMeasureDayweekmonthyear_2_SMQ,CurrentSelfreportedHeightInches,CurrentSelfreportedWeightPounds,TriedToLoseWeightInPastYear,TimesLost10LbsOrMoreToLoseWeight
0,93703.0,NaN,1.0,273.0,1.0,365.0,152.0,365.0,Whole or regular milk,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,93704.0,NaN,1.0,60.0,3.0,365.0,126.0,365.0,Whole or regular milk,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,93705.0,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,63.0,165.0,0.0,11 times or more
3,93706.0,Very good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,68.0,145.0,0.0,Never
4,93707.0,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df10.columns

Index(['SEQN', 'GeneralHealthCondition', 'EverBreastfedOrFedBreastmilk',
       'AgeStoppedBreastfeedingdays', 'AgeFirstFedFormuladays',
       'AgeStoppedReceivingFormuladays', 'AgeStartedOtherFoodbeverage',
       'AgeFirstFedMilkdays', 'TypeOfMilkFirstFedWholeMilk',
       'TypeOfMilkFirstFed2Milk',
       ...
       'DaysSmokedCigsDuringPast30Days', 'AvgCigarettesdayDuringPast30Days',
       'TriedToQuitSmoking', 'TimesStoppedSmokingCigarettes',
       'HowLongWereYouAbleToStopSmoking',
       'UnitOfMeasureDayweekmonthyear_2_SMQ',
       'CurrentSelfreportedHeightInches', 'CurrentSelfreportedWeightPounds',
       'TriedToLoseWeightInPastYear', 'TimesLost10LbsOrMoreToLoseWeight'],
      dtype='str', length=198)

In [21]:
df10_new = df10[(df10['AgeInYearsAtScreening'] >= 18) & df10['SleepHoursWeekdaysOrWorkdays'].notna()]
sleep = df10_new['SleepHoursWeekdaysOrWorkdays'].mean()
print(f'Estimated mean sleep for people >=18 years age on weekdays = {round(sleep,3)}')

Estimated mean sleep for people >=18 years age on weekdays = 7.621

In [23]:
week_sleep = df10_new['SleepHoursWeekdaysOrWorkdays'].to_numpy()
n = len(week_sleep)
bootstrap10 = []

for i in range(R):
    week_sleep_b = rng.choice(week_sleep, size=n, replace=True)
    mean_b10 = week_sleep_b.mean()
    bootstrap10.append(mean_b10)

In [24]:
se_hat10 = np.std(bootstrap10, ddof=1)
se_hat10

np.float64(0.022796963558777535)

In [25]:
for i,j in ci.items():
    lower10 = sleep - j * se_hat10
    upper10 = sleep + j * se_hat10
    print(f'For {i}% confidence interval is ({round(lower10,3)},{round(upper10,3)})')

    if lower10 < 8 < upper10:
        print(f'For {i}% : Value within CI. Fail to reject null hypothesis')
    else:
        print(f'For {i}% : Reject null hypothesis')

For 90% confidence interval is (7.584,7.659)
For 90% : Reject null hypothesis
For 95% confidence interval is (7.577,7.666)
For 95% : Reject null hypothesis
For 99% confidence interval is (7.563,7.68)
For 99% : Reject null hypothesis